fbschema = {'timestamp': {'type': 'integer'}, 'data': [{'post': {'type': 'string'}}],
            'attachments': [{'data': [{'media': {'uri': {'type': 'string'},
                                                 'status': {'type': 'string'},
                                                 'creation_timestamp': {'type': 'integer'},
                                                 'media_metadata': {'photo_metadata': {
                                                     'camera_model': {'type': 'string'},
                                                     'original_height': {'type': 'number'},
                                                     'camera_make': {'type': 'string'},
                                                     'modified_timestamp': {'type': 'number'},
                                                     'upload_ip': {'type': 'string'},
                                                     'exposure': {'type': 'string'},
                                                     'original_width': {'type': 'number'},
                                                     'iso_speed': {'type': 'number'},
                                                     'f_stop': {'type': 'string'},
                                                     'longitude': {'type': 'number'},
                                                     'taken_timestamp': {'type': 'number'},
                                                     'focal_length': {'type': 'string'},
                                                     'orientation': {'type': 'number'},
                                                     'latitude': {'type': 'number'}}},
                                                 'description': {'type': 'string'}}}]}]}
